TextInput:  added the theme components to be updated for anyones cases
Baby-Yoda-RN/food-hub pull request #10
Opened 2022-04-22 18:41 UTC by raynesmike

This component will require the input type: 'phone' | 'password' | 'email' | 'regular' | 'search'. so that it can handle multiple type of input. it can also take icons to add more cases. //TODO for passwords.

2022-04-22 20:30 UTC, Nap1400 approved these changes

2022-04-22 22:31 UTC, lasharela requested changes

2022-04-22 22:31 UTC, lasharela commented on mobile/src/components/textInput/TextInput.style.ts
> +import {color, size} from '../../theme';
Good. we have this object finally

2022-04-22 22:31 UTC, lasharela commented on mobile/src/components/textInput/TextInput.style.ts
> +type Styles = {
For style there is built in style. check LEO's PR... or google it. Style type in RN

2022-04-22 22:31 UTC, lasharela commented on mobile/src/components/textInput/TextInput.style.ts
> +export const style: Styles = {
ah, this doesn't really need any style at all. inside of it, if you'll have any view or Text you can use RN built in styles.

2022-04-22 22:31 UTC, lasharela commented on mobile/src/components/textInput/TextInput.tsx
> +  const [containerStyle, setContainerStyle] = useState([style.container]);
never, evre save style in state. no idea what you are doing but save something if you want. for example if Button is disabled and based on this variable apply 2 different styles. Style is not, can't be state of the component. it's just visual style. why you have to save it?

2022-04-22 22:31 UTC, lasharela commented on mobile/src/components/textInput/TextInput.tsx
> +  const [text, setText] = useState('');
no idea what's goin on here. see bunch of messy functionality :D we'll see together while class. try to export some functionality if possible as utility function. for example phone validation

2022-04-22 22:31 UTC, lasharela commented on mobile/src/components/textInput/TextInput.tsx
> +      {leftIcon && (
if by mistake leftIcon will be provided empty object or undefined this will throw an error. 

!!leftIcon - is better

2022-04-22 22:31 UTC, lasharela commented on mobile/src/components/textInput/TextInput.tsx
> +        onChangeText={e => onTextChange(e)}
onChangeText={onTextChange}

this won't work? of course, it will... why? Answer this while in class.

2022-04-22 22:56 UTC, raynesmike commented on mobile/src/components/textInput/TextInput.tsx
> +      {leftIcon && (
Thank you I forgot to check for that actually

2022-04-23 00:45 UTC, mshago approved these changes

2022-04-23 00:45 UTC, Dulaya approved these changes

2022-04-23 00:45 UTC, merged