Button
Baby-Yoda-RN/food-hub pull request #16
Opened 2022-04-23 03:33 UTC by leo-he-1

2022-04-23 14:51 UTC, Dulaya commented
For the record, we communicated outside of Github.

Sorry I wasn't clear last time. Leo, I think you can change the leftIcon to **leftIconName** (same for rightIcon) to make it clearer. 

Also you need to pass external sizes as props instead of doing width={size.lg} like this with default value: **leftIconWidth=size.lg**, leftIconHeight=size.lg, etc. Then you can just do **with={leftIconWith}**. Same for right icon.

Icon can also accepts another prop named **containerStyle**. You need to pass that too in icon like this <Icon **containerStyle={containerStyle}** />

Lastly, don't forget to post a **screenshot**. Let me know if you have any questions.

2022-04-23 15:18 UTC, raynesmike commented on mobile/src/theme/size/size.ts
> +  xl: 28,
you might need to rename it using the original one, but change the values if we need to. i think this will make the other component using this have an error since it doesnt use this new naming

2022-04-23 15:29 UTC, leo-he-1 commented on mobile/src/theme/size/size.ts
> +  xl: 28,
I'm going to change it back to the one we have.

2022-04-23 16:22 UTC, leo-he-1 commented
![image](https://user-images.githubusercontent.com/70768391/164914549-386de2a5-1914-4250-9766-e6553764d4ec.png)

2022-04-24 04:01 UTC, Dulaya approved these changes
I'm not sure why you did the switch case, but everything works find for me.

2022-04-25 07:28 UTC, mshago approved these changes

2022-04-25 17:10 UTC, carizzuti approved these changes

2022-04-25 22:34 UTC, aahenry51 approved these changes

2022-04-25 23:50 UTC, lasharela requested changes

2022-04-25 23:50 UTC, lasharela commented on mobile/App.tsx
> +        iconWidth = {20}
what if button will have size inside and won't provide from outside? what if we'll keep size based on button size.

2022-04-25 23:50 UTC, lasharela commented on mobile/src/components/button/Button.tsx
> +  onPress,
for `onPress` can't we just spread `...rest`?

2022-04-25 23:50 UTC, lasharela commented on mobile/src/components/button/Button.tsx
> +  let buttonClickableStyle = isDisabled ? styles.buttonDisabled : styles.buttonEnabled;
both might be `const`

2022-04-26 00:03 UTC, leo-he-1 commented on mobile/src/components/button/Button.tsx
> +  buttonOutlineColor = 'white',
You are correct. I have made the change.

2022-04-26 00:26 UTC, merged