TextInput: Updated v.1
Baby-Yoda-RN/food-hub pull request #18
Opened 2022-04-25 16:26 UTC by raynesmike

Following added:
added Icons to the text input
separated a working utility for phone type
useRef to focus textinput when clicking anywhere in the component
password security sensitivity pressIn/pressout

2022-04-25 19:53 UTC, carizzuti approved these changes

2022-04-25 23:47 UTC, lasharela requested changes

2022-04-25 23:47 UTC, lasharela commented on mobile/src/components/textInput/TextInput.tsx
>    const [isActive, setIsActive] = useState(Boolean);
here you are setting by default value. if you want to set by default type you have to do 

useState<boolean>(false) (Do we need capital letter for types? )

2022-04-25 23:47 UTC, lasharela commented on mobile/src/components/textInput/TextInput.tsx
> +  useLayoutEffect(() => {
I would say you have to create 2 components. `TextInput` and `TextInputPassword`...

2022-04-25 23:47 UTC, lasharela commented on mobile/src/utilities/phone_validator.ts
> +export const phone_validator = (input: string) => {
what is return type of this method?

2022-04-26 01:21 UTC, raynesmike commented on mobile/src/utilities/phone_validator.ts
> +export const phone_validator = (input: string) => {
Thank you, Ill makesure to add that

2022-04-26 04:46 UTC, raynesmike commented on mobile/src/components/textInput/TextInput.tsx
>    const [isActive, setIsActive] = useState(Boolean);
That make sense, for readability. Thank you

2022-04-26 04:48 UTC, raynesmike commented on mobile/src/components/textInput/TextInput.tsx
> +  useLayoutEffect(() => {
Is this a bad practice to create 1 component for the textInput? I just added a logic to set isSensitive(securedText) to hide the password

2022-04-26 09:20 UTC, Dulaya commented
- The biggest I saw was: Do you have a way to retrieve the input value? I know you can use ...rest. However, whoever will build the screens will get type errors especially if they pass down useState function. One way to solve this problem is to explicitly create a way to pass down the function in addition to using rest.
- Another issue is that the phone number input is very buggy. 
- Some random type errors (Maybe it's just on my local development).
- Lastly, the text input and icons are really big on my screen. See picture.
- Overall, everything else work fine. I had no issues with the Email, Password and Search input. Good work.

![image](https://user-images.githubusercontent.com/50040948/165267130-4dcb67b9-521e-4bfd-b49a-6be8f7980c37.png)

2022-04-27 23:32 UTC, Nap1400 approved these changes

2022-04-27 23:54 UTC, aahenry51 approved these changes

2022-04-27 23:59 UTC, merged