WIP: Order Card
Baby-Yoda-RN/food-hub pull request #28
Opened 2022-04-26 22:46 UTC by mshago

2022-04-26 23:27 UTC, mshago commented
![image](https://user-images.githubusercontent.com/36893258/165408988-d33ab1e0-cbee-4121-a93c-54c73d6a0f7b.png)

2022-04-27 02:02 UTC, lasharela requested changes

2022-04-27 02:02 UTC, lasharela commented on mobile/src/components/orderCard/OrderCard.styles.ts
> +    fontWeight: '600',
Use fobt family instead

2022-04-27 05:18 UTC, Dulaya commented
Suggestions:
 * Change minWidth: 45% in button to flex: 1
 * Change order.items from array to just number. This will help make it easier to understand for whoever will My Order screen. 
 * Add the green little checkmark next to Starbuck name:

         <View style={{flexDirection: 'row' }}>
            <Text style={styles.restaurantText}>{order.restaurantName}</Text>
            <Icon name="CheckMark" width={8} height={8} />
         </View>

![image](https://user-images.githubusercontent.com/50040948/165445724-973b6412-e7be-4ffb-87f2-b4403a2104a6.png)

 * Use the Icon for bullet point instead (Don't do inline style; Also notice bigger gree bullet):
 
         {delivered && (
            <View style={{flexDirection: 'row', alignItems: 'center'}}>
               <Icon containerStyle={{padding:0, marginRight: 5}} name="Bullet" width={8} height={8} fill="#4EE476" />
               <Text style={styles.orderStatusText}>{order.status}</Text>
            </View>
         )}

![image](https://user-images.githubusercontent.com/50040948/165445613-6e037770-b454-4467-95d2-a813ce5e3844.png)

* Some minor style changes.

2022-04-27 05:19 UTC, Dulaya approved these changes

2022-04-27 19:08 UTC, mshago commented on mobile/src/components/orderCard/OrderCard.tsx
> +        <View style={{width: '50%', justifyContent: 'space-evenly'}}>
done

2022-04-27 19:08 UTC, mshago commented on mobile/src/components/orderCard/OrderCard.tsx
> +            style={{color: color.black, fontWeight: '600', fontSize: size.m}}>
done

2022-04-27 19:23 UTC, mshago commented on mobile/src/components/orderCard/OrderCard.tsx
> +          title={delivered?'Rate':'Cancel'}
done

2022-04-27 22:31 UTC, Nap1400 approved these changes

2022-04-27 23:12 UTC, Nap1400 approved these changes

2022-04-27 23:16 UTC, leo-he-1 approved these changes

2022-04-27 23:16 UTC, leo-he-1 commented on mobile/src/components/button/Button.type.ts
> +    titleStyle?: StyleProp<TextStyle>;
Thank you for showing me this change.

2022-04-27 23:20 UTC, carizzuti approved these changes
This all looks good, I don't see any issues.

2022-04-27 23:22 UTC, aahenry51 approved these changes

2022-04-27 23:24 UTC, mshago commented on mobile/src/components/orderCard/OrderCard.styles.ts
> +    fontWeight: '600',
done

2022-04-27 23:46 UTC, merged