Tag: Price Tag and Rating Tag components
Baby-Yoda-RN/food-hub pull request #29
Opened 2022-04-26 23:20 UTC by carizzuti

Different tags for the price and the rating.

![image](https://user-images.githubusercontent.com/61713261/165408306-a8098531-96bd-48da-9468-a9e4585682fe.png)

2022-04-26 23:23 UTC, Nap1400 approved these changes

2022-04-26 23:23 UTC, Nap1400 commented on mobile/src/components/tag/Tag.style.tsx
> +    fontSize: size.rg,
This will be a different size when implemented in the screens, correct

2022-04-26 23:26 UTC, carizzuti commented on mobile/src/components/tag/Tag.style.tsx
> +    fontSize: size.rg,
Actually it looks like I forgot to add a style prop

2022-04-27 07:03 UTC, Dulaya commented
* Don't forget to export them from index.ts
* In container, replace paddingHorizontal: size.xs with padding: size.sm (8). Both horizontal and vertical have about same padding. 
* In container, remove borderWidth. 
* Create another type and prop named shadowEnable?: boolean. If shadowEnable, then show shadow. Else, hide shadow. Inside Tag.tsx:

        <View
          style={[
            styles.container,
            containerStyle,
            shadowEnable && {shadowColor: color.grayMid, elevation: 5},
          ]}>
          {renderTag()}
        </View>

* Optional: add margin: size.xxs to the numbers. Play around to find best look.

![image](https://user-images.githubusercontent.com/50040948/165460401-47df7b3f-1794-4eeb-8888-30ec604400b5.png)

2022-04-27 07:04 UTC, Dulaya approved these changes

2022-04-27 23:17 UTC, mshago commented on mobile/src/theme/color/color.ts
> +  transparentBlack: 'rgba(0, 0, 0, 0.1)',
do you need this color?

2022-04-27 23:21 UTC, lasharela requested changes

2022-04-27 23:22 UTC, carizzuti commented on mobile/src/theme/color/color.ts
> +  transparentBlack: 'rgba(0, 0, 0, 0.1)',
At first I was using it but I changed the shadow style

2022-04-27 23:27 UTC, mshago approved these changes

2022-04-27 23:34 UTC, carizzuti commented on mobile/src/components/tag/Tag.tsx
> +  rating = 4.5,
I removed that, made it optional.

2022-04-27 23:35 UTC, merged

2022-04-27 23:35 UTC, aahenry51 approved these changes