WIP: Home Screen
Baby-Yoda-RN/food-hub pull request #36
Opened 2022-04-28 00:42 UTC by mshago

2022-04-28 22:50 UTC, mshago commented
![image](https://user-images.githubusercontent.com/36893258/165860377-eeefc6da-9056-4ec0-88e6-c8a451547d53.png)

2022-04-28 23:42 UTC, mshago commented
![image](https://user-images.githubusercontent.com/36893258/165864712-7cf48f37-59b6-473e-b402-d8ebb01ba963.png)

2022-04-29 23:35 UTC, Josetf2396 approved these changes

2022-04-30 05:37 UTC, Nap1400 approved these changes

2022-04-30 14:01 UTC, mshago commented
![image](https://user-images.githubusercontent.com/36893258/166108612-00cd7f98-3f57-4b8d-9d97-ba3e0e86c4a4.png)

2022-04-30 15:53 UTC, lasharela requested changes

2022-04-30 15:53 UTC, lasharela commented on mobile/ios/mobile.xcodeproj/project.pbxproj
> +<<<<<<< HEAD
this is an unresolved conflict... this file needs to be excluded because as I remember we already implemented all fonts. you can just reset this fail or pickup from the remote. 

and this <<<<< is unresolved conflict. never ever push this :)

2022-04-30 15:53 UTC, lasharela commented on mobile/ios/mobile.xcodeproj/project.pbxproj
> +>>>>>>> origin/main
the same

2022-04-30 16:01 UTC, lasharela approved these changes

2022-05-02 22:59 UTC, mshago commented
![image](https://user-images.githubusercontent.com/36893258/166339845-1a92b415-b345-404f-b7f3-8a429d39a3f7.png)

2022-05-03 00:02 UTC, lasharela approved these changes

2022-05-03 01:00 UTC, raynesmike approved these changes

2022-05-03 01:01 UTC, Dulaya approved these changes

2022-05-03 01:02 UTC, merged