WIP: Profile Screen
Baby-Yoda-RN/food-hub pull request #44
Opened 2022-04-28 02:25 UTC by Josetf2396

2022-04-28 23:28 UTC, Josetf2396 commented
![image](https://user-images.githubusercontent.com/44705680/165863648-76d362ed-0381-449a-8581-11f2d2e867cd.png)

2022-05-07 15:27 UTC, lasharela commented
We need button here as well. Action button

2022-05-09 23:53 UTC, lasharela requested changes

2022-05-09 23:53 UTC, lasharela commented on mobile/src/screens/profile/Profile.view.tsx
> +    <>
you don't need this

2022-05-09 23:53 UTC, lasharela commented on mobile/src/screens/profile/Profile.view.tsx
> +        <Button
footer prop of Container component

2022-05-09 23:53 UTC, lasharela commented on mobile/src/screens/profile/profileDummyData.ts
> +export const profileDummyData = [
move to backend

2022-05-09 23:53 UTC, lasharela commented on mobile/src/screens/profile/Profile.view.tsx
> +              onChangeText={function (value: string): void {
function - keep consistency and use ()=>

onChangeText={(value: string): void => {

2022-05-09 23:53 UTC, lasharela commented on mobile/src/screens/profile/Profile.view.tsx
> +              value={''}
no empty string please

2022-05-11 22:58 UTC, closed without merging