WIP: Rating Screen
Baby-Yoda-RN/food-hub pull request #46
Opened 2022-04-28 21:26 UTC by Nap1400

Currently empty screen, I accidentally merged with main last commit rather than creating a new PR. This is meant to be for all four Rating files.

2022-05-03 22:01 UTC, Nap1400 commented
![image](https://user-images.githubusercontent.com/68311219/166573614-311fabd0-247a-40c9-81c7-74f4fbd66b1f.png)

2022-05-09 20:25 UTC, carizzuti approved these changes

2022-05-09 20:26 UTC, leo-he-1 commented on mobile/src/screens/rating/Rating.type.ts
> +import { TRestaurant } from '../../types/data';
Were you using TRestaruant, EAppNavigationRoutes, TAppNavigationRoutes, and StackScreenProps for testing? Doesn't seem like they are being used anymore

2022-05-09 20:26 UTC, leo-he-1 commented on mobile/src/screens/rating/Rating.view.tsx
> +            backgroundImage={require('../../assets/images/pizza_hut.png')}
I think Lasha wants references like this to be an export. I did something similar in my pr https://github.com/Baby-Yoda-RN/food-hub/pull/53/files. Its in the images.ts file.

2022-05-09 20:26 UTC, leo-he-1 commented on mobile/src/screens/rating/Rating.view.tsx
>  import { Text,View,TouchableOpacity,Image } from "react-native";
Looks like some of these imports are not being used.

2022-05-09 20:26 UTC, leo-he-1 approved these changes

2022-05-09 21:47 UTC, Dulaya requested changes
- I know you did not work on the Container component, but you have to change the ImageBackground in Container component to include imageStyle={imageStyle}. This will allows you to edit the borderRadius of the background image.
   - Make sure you edit the Container.type.ts also to include imageStyle.
- In Rating.view.tsx:
   - You have to add Header to Container and make sure the left icon navigate to previous screen.
   - The Pizza Hut icon needs a borderWidth and the green checkmark icon. 
   - You need to fix the paddings/margins through the screen. 
   - You need the green bullet point at Order Delivered. 
   - Make sure the Start Rating component works just like the Restaurant Review screen you did.
   - Button needs rounder borderRadius. 
- You have a lot of unused imports. 
![Screenshot_1652130309](https://user-images.githubusercontent.com/50040948/167504048-6eb8c366-cb66-4c44-bbc9-380a6ee196fe.png)

2022-05-11 23:29 UTC, raynesmike commented on mobile/src/components/container/Container.tsx
> +        imageStyle={imageStyle}
Thanks for adding this style for the imageStyle for the container.

2022-05-11 23:41 UTC, Josetf2396 approved these changes

2022-05-12 00:08 UTC, Dulaya approved these changes

2022-05-12 00:08 UTC, merged