WIP: Add New Address Screen
Baby-Yoda-RN/food-hub pull request #54
Opened 2022-04-29 21:07 UTC by Josetf2396

2022-05-02 23:49 UTC, lasharela requested changes

2022-05-02 23:49 UTC, lasharela commented on mobile/src/screens/addNewAddress/addNewAddress.tsx
> +      name='Eljad Eendaz'
Needs to be props for main component.

2022-05-03 23:42 UTC, raynesmike approved these changes

2022-05-06 00:02 UTC, Josetf2396 commented on mobile/src/screens/addNewAddress/addNewAddress.style.ts
> +        padding: size.rg,
remove padding

2022-05-06 00:05 UTC, lasharela requested changes

2022-05-06 00:05 UTC, lasharela commented on mobile/src/screens/addNewAddress/addNewAddress.view.tsx
> +        <Text style={styles.text}>Full name</Text>
<Section>Wrapp rest here</Section>

2022-05-06 00:05 UTC, lasharela commented on mobile/src/screens/addNewAddress/addNewAddress.view.tsx
> +        <Text style={styles.text}>Full name</Text>
== View == 
topSize
topReset

bottomSize
bottomReset

verticalSize
verticalReset

2022-05-09 23:48 UTC, lasharela approved these changes

2022-05-09 23:48 UTC, lasharela commented on mobile/src/screens/addNewAddress/addNewAddress.style.ts
> +        shadowColor: color.black,
on iOS this won't work

2022-05-09 23:48 UTC, lasharela commented on mobile/src/screens/addNewAddress/addNewAddress.type.ts
> +    goBack?: () => void;
() => void  
Function 

saveButton?: () => void;

const myMethod = {()=> {do something)}
<Component
saveButton={myMethod} />

2022-05-09 23:48 UTC, lasharela commented on mobile/src/screens/addNewAddress/addNewAddress.view.tsx
> +      <View style={styles.container}>
<View style={styles.container}>

2022-05-12 23:59 UTC, lasharela approved these changes

2022-05-12 23:59 UTC, Dulaya approved these changes

2022-05-12 23:59 UTC, mshago approved these changes

2022-05-13 00:00 UTC, aahenry51 approved these changes

2022-05-13 00:42 UTC, merged