Radio Button
Baby-Yoda-RN/food-hub pull request #58
Opened 2022-04-29 23:03 UTC by mshago

![image](https://user-images.githubusercontent.com/36893258/166078883-4b99a72d-4bed-4309-9607-f97595f8f049.png)

2022-04-29 23:07 UTC, lasharela requested changes

2022-04-29 23:07 UTC, lasharela commented on mobile/src/components/button/radioButton/RadioButton.style.ts
> +  img: {
maybe `image` or `imageContainer` - full name and keep it consistent?

2022-04-29 23:07 UTC, lasharela commented on mobile/src/components/button/radioButton/RadioButton.style.ts
> +  unselected: {
maybe by default it will be just as it is and if only it's `isSelected` then we'll change styles? `unselected` style sounds weird

2022-04-29 23:07 UTC, lasharela commented on mobile/src/components/button/radioButton/RadioButton.tsx
> +    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={containerStyle}>
I think we have to have single element as separate one, and rest of the staff (ScrollView and etc) will be part of the screen. here we have to have only single element. I mention this last time.

2022-04-29 23:34 UTC, Josetf2396 approved these changes

2022-04-29 23:38 UTC, mshago commented on mobile/src/components/button/radioButton/RadioButton.tsx
> +    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={containerStyle}>
done

2022-04-29 23:38 UTC, mshago commented on mobile/src/components/button/radioButton/RadioButton.style.ts
> +  unselected: {
done

2022-04-29 23:38 UTC, mshago commented on mobile/src/components/button/radioButton/RadioButton.style.ts
> +  img: {
done

2022-04-29 23:46 UTC, Nap1400 approved these changes

2022-04-30 00:46 UTC, Dulaya approved these changes

2022-04-30 00:46 UTC, merged