Review Screen
Baby-Yoda-RN/food-hub pull request #67
Opened 2022-05-02 19:08 UTC by carizzuti

Created Review Screen, currently using dummy data.

![Screenshot_1651518424](https://user-images.githubusercontent.com/61713261/166309522-de9aa5a8-24b5-4e24-a098-990d102c3c4e.png)

2022-05-02 20:29 UTC, raynesmike commented on mobile/src/components/textInput/TextInput.tsx
> +  let max = type === 'phone' ? 17 : 300;
Why did you change this charlie? this was meant for the logic for the length of phone number.

2022-05-02 20:32 UTC, raynesmike commented on mobile/src/components/textInput/TextInput.tsx
> +  let max = type === 'phone' ? 17 : 300;
I should probably update this textInput. and handle everything inside the switch.

2022-05-02 21:22 UTC, Dulaya commented
- Your ChevronLeft icon is a little off to the right.
- Okay to remove `TReviewScreenProps` in Review.type.ts if you're not using it: 

         export type TReviewScreenProps = StackScreenProps<
            TAppNavigationRoutes,
            EAppNavigationRoutes.REVIEW
         >;
- Optional: 
   - Shorten the review texts, or use ... That way, you can see more reviews. 
   - Your Review Card has unnecessary margin. It should be aligned with the TextInput:
![image](https://user-images.githubusercontent.com/50040948/166329811-a40d045e-f881-4115-9d90-1c74879fef39.png)
- No major issues besides styling. Good job. ✔️

2022-05-02 21:22 UTC, Dulaya approved these changes

2022-05-02 23:39 UTC, lasharela requested changes

2022-05-02 23:39 UTC, lasharela commented on mobile/App.tsx
>      setTimeout(() => {}, 1000);
try to remove

2022-05-03 20:10 UTC, Josetf2396 approved these changes

2022-05-03 20:15 UTC, Nap1400 approved these changes

2022-05-03 20:41 UTC, merged