Verify update
Baby-Yoda-RN/food-hub pull request #75
Opened 2022-05-04 00:03 UTC by aahenry51

2022-05-04 00:10 UTC, mshago commented on mobile/src/screens/verify/Verify.view.tsx
>        <Header
you don't need the second header right?

2022-05-04 01:54 UTC, Josetf2396 approved these changes

2022-05-04 01:54 UTC, raynesmike approved these changes
I approve this

2022-05-04 06:13 UTC, mshago approved these changes

2022-05-07 15:15 UTC, lasharela requested changes

2022-05-07 15:15 UTC, lasharela commented on mobile/src/screens/foodDetails/FoodDetails.tsx
> +export const FoodDetailsScreen: FC<TFoodDetailsNavigation> = ({navigation}) => {
navigation is not used

2022-05-07 15:15 UTC, lasharela commented on mobile/src/screens/foodDetails/FoodDetails.view.tsx
> +    <View>
maybe you'll try Container and head prop instead?

2022-05-07 15:15 UTC, closed without merging