Category Screen
Baby-Yoda-RN/food-hub pull request #76
Opened 2022-05-04 02:43 UTC by raynesmike

Updated and fix Category Screen

2022-05-05 05:10 UTC, Dulaya approved these changes

2022-05-05 21:17 UTC, Nap1400 approved these changes

2022-05-05 23:01 UTC, mshago commented on mobile/src/components/dropdown/Dropdown.tsx
>    const [open, setOpen] = useState(false);
states should be outside de component

2022-05-05 23:01 UTC, Josetf2396 approved these changes

2022-05-05 23:02 UTC, mshago commented on mobile/src/screens/category/Category.styles.ts
> +    fontWeight: 'bold',
use fontFamily

2022-05-05 23:57 UTC, lasharela requested changes

2022-05-05 23:57 UTC, lasharela commented on mobile/src/screens/category/Category.view.tsx
> +      <Container
check header prop

2022-05-05 23:57 UTC, lasharela commented on mobile/src/screens/category/Category.view.tsx
> +              <Dropdown data={DropdownList}></Dropdown>
<Dropdown data={DropdownList} />

2022-05-06 03:55 UTC, raynesmike commented on mobile/src/components/dropdown/Dropdown.tsx
>    const [open, setOpen] = useState(false);
Thank you, but I think for this should it should be inside because this will be initially set the dropdown as closed

2022-05-06 03:57 UTC, merged