WIP: Header
Baby-Yoda-RN/food-hub pull request #8
Opened 2022-04-22 02:30 UTC by Josetf2396

2022-04-22 20:39 UTC, raynesmike approved these changes
Everything seems good, We just need to update couple things once theme is added

2022-04-25 17:08 UTC, carizzuti commented on mobile/src/components/header/Header.tsx
> +  rightIconStyle: any;
Consider not using `any` type. With this a string or number can be passed in with no error.

2022-04-25 23:27 UTC, Nap1400 approved these changes

2022-04-26 00:01 UTC, lasharela requested changes

2022-04-26 00:01 UTC, lasharela commented on mobile/src/components/header/Header.tsx
> +interface IProps {
why we need interface and not type... if you are trying to extend existing type of the header that's not the way to go. we don't really need to extend and even if we need, we have to do this differently. try to google how to extend typescript types and interfaces.

2022-04-26 00:01 UTC, lasharela commented
Visually it looks more complicated

2022-04-27 23:54 UTC, carizzuti approved these changes

2022-04-27 23:54 UTC, merged