Favorite Food Items with Toggle
Baby-Yoda-RN/food-hub pull request #80
Opened 2022-05-05 23:24 UTC by leo-he-1

2022-05-05 23:46 UTC, leo-he-1 commented
![image](https://user-images.githubusercontent.com/70768391/167044511-6b1d1873-aa68-47e4-a478-93bad21be73e.png)

2022-05-05 23:47 UTC, leo-he-1 commented
![image](https://user-images.githubusercontent.com/70768391/167044550-df93d614-9cdd-40d3-9ea7-908d4f68ab24.png)

2022-05-05 23:50 UTC, lasharela requested changes

2022-05-05 23:50 UTC, lasharela commented on mobile/src/screens/favoriteFoodItems/FavoriteFoodItems.styles.ts
> +        width: 160,
Not fixed? fixed?

2022-05-05 23:50 UTC, lasharela commented on mobile/src/screens/favoriteFoodItems/FavoriteFoodItems.tsx
> +  const [option, setOption] = useState<boolean>(true)
set more descriptive name pls

2022-05-05 23:50 UTC, lasharela commented on mobile/src/screens/favoriteFoodItems/FavoriteFoodItems.type.ts
> +    favoriteFoodItems:Array<Object>
[TMyFoodItems]
+ TMyFoodItems[]
+ String[]

2022-05-05 23:50 UTC, lasharela commented on mobile/src/screens/favoriteFoodItems/FavoriteFoodItems.view.tsx
> +        <Container isLoading={isLoading}>
<Container isLoading={isLoading} header={...componentHere}>

2022-05-06 17:46 UTC, Josetf2396 approved these changes

2022-05-07 00:01 UTC, Dulaya approved these changes

2022-05-07 00:02 UTC, Dulaya commented
- In FavoriteFoodItems.view, you have an un used onPress. Add onPress={onPress} to TouchableOpacity.

Optional: 

 - If FavoriteFoodItems.tsx, you can pass this code as prop to FavoriteFoodItemScreenView:
 - 
            leftPress={() => navigation.goBack()}

      - Make sure you add to the type file with type () => void
   - In Header, you and do leftPress={leftPress}
      - This will cause an error for now because there's no route to back to anything yet.

 - In FavoriteFoodItems.view, remove unnecessary codes (View, return). This code work same as your code: 

            {(showFavoriteFoods ? favoriteFoodItems : favoriteResturants).map((food, index) => 
               <TouchableOpacity key={String(index)}>
                  <FoodCard foodItem={food} />
               </TouchableOpacity>
            )}

 - In Header, you can pass picture like this instead of using rightIconName:
      rightIconLocation="https://i.imgur.com/EQn7qGf.png"

2022-05-07 05:29 UTC, Nap1400 approved these changes

2022-05-07 05:29 UTC, merged