WIP: Restaurant Review Screen
Baby-Yoda-RN/food-hub pull request #88
Opened 2022-05-07 16:29 UTC by Nap1400

![image](https://user-images.githubusercontent.com/68311219/167263310-556c4a27-a142-420e-a559-27ca2275e188.png)

2022-05-09 20:20 UTC, carizzuti approved these changes
Screen looks good, next we should work on configuring axios for this screen. Will be a post request to the review endpoint.

2022-05-09 20:40 UTC, Dulaya commented
- In RestaurantReview.view.tsx:
   - You have a lot of unused imports. Delete them if you're not using the imports.
   - SafeAreaView should be import from 'react-native'
   - Don't use inline styling.
   - You should get your image from your end point. Also pizza_hut_logo.png doesn't exist. 
   - The button needs rounder borderRadius.
   - You need to use Header inside the Container. Make sure the back button navigate to previous screen. 

- In RestaurantReview.type.ts:
   - You also have a lot of unsed imports. Delete them if they're not being used.

- In RestaurantReview.tsx:
   - You need to pass your data from here to the RestaurantReview.view.tsx as props instead of hard-coding them there.

2022-05-09 20:41 UTC, Dulaya requested changes
- In RestaurantReview.view.tsx:
   - You have a lot of unused imports. Delete them if you're not using the imports.
   - SafeAreaView should be import from 'react-native'
   - Don't use inline styling.
   - You should get your image from your end point. Also pizza_hut_logo.png doesn't exist. 
   - The button needs rounder borderRadius.
   - You need to use Header inside the Container. Make sure the back button navigate to previous screen. 

- In RestaurantReview.type.ts:
   - You also have a lot of unsed imports. Delete them if they're not being used.

- In RestaurantReview.tsx:
   - You need to pass your data from here to the RestaurantReview.view.tsx as props instead of hard-coding them there.

2022-05-09 23:29 UTC, lasharela approved these changes

2022-05-09 23:29 UTC, lasharela commented on mobile/src/screens/restaurantReview/RestaurantReview.style.ts
> +    buttonContainer: {
review this

2022-05-09 23:29 UTC, lasharela commented on mobile/src/screens/restaurantReview/RestaurantReview.view.tsx
> +            style={{
no inline styles

2022-05-09 23:29 UTC, lasharela commented on mobile/src/screens/restaurantReview/RestaurantReview.view.tsx
> +            source={require('../../assets/images/pizza_hut_logo.png')}
create index.ts inside of assets

2022-05-09 23:29 UTC, lasharela commented on mobile/src/screens/restaurantReview/RestaurantReview.view.tsx
> +        type={'regular'}
remove this

2022-05-10 20:36 UTC, raynesmike approved these changes

2022-05-11 23:28 UTC, raynesmike commented on mobile/src/screens/restaurantReview/RestaurantReview.view.tsx
> +      <SafeAreaView>
c

2022-05-11 23:28 UTC, lasharela requested changes

2022-05-11 23:28 UTC, lasharela commented on mobile/src/screens/restaurantReview/RestaurantReview.view.tsx
> +          style={{
no inline styles

2022-05-11 23:28 UTC, lasharela commented on mobile/src/screens/restaurantReview/RestaurantReview.view.tsx
> +                  height: 100,
same

2022-05-11 23:38 UTC, Josetf2396 approved these changes

2022-05-12 00:07 UTC, Dulaya approved these changes

2022-05-12 00:07 UTC, merged