WIP: Bottom Tab Navigator
Baby-Yoda-RN/food-hub pull request #9
Opened 2022-04-22 17:33 UTC by mshago

Blocker: waiting on the icons and the badge component

2022-04-22 18:45 UTC, raynesmike commented on mobile/src/components/bottomTabNavigator/BottomTabNavigator.tsx
> +const styles = StyleSheet.create({
I think we need to separate the styles with a .ts extensions.

2022-04-22 20:21 UTC, raynesmike approved these changes
I approve this addition

2022-04-25 19:52 UTC, carizzuti approved these changes

2022-04-25 23:58 UTC, lasharela requested changes

2022-04-25 23:58 UTC, lasharela commented on mobile/src/components/bottomTabNavigator/BottomTabNavigator.tsx
> +    Alert.alert('Pressed')
do we have to have this alert here?

2022-04-25 23:58 UTC, lasharela commented on mobile/src/components/bottomTabNavigator/BottomTabNavigator.tsx
> +        <Icon name="Compass" height={SIZE} width={SIZE} fill={PRIMARY_COLOR} />
why do we have local SIZE... some times it's needed. just asking. why not to set directly size something.

2022-04-25 23:58 UTC, lasharela commented on mobile/src/components/bottomTabNavigator/BottomTabNavigator.type.ts
> +  state?:string,
I can't figure out what state is about? whhy it needs to be provided from outside?

2022-04-25 23:58 UTC, lasharela commented on mobile/src/components/bottomTabNavigator/BottomTabNavigator.type.ts
> +export type BottomTabNavigatorProps = {
for types maybe we'll use TBottom...etc (T in front)

2022-04-26 00:07 UTC, mshago commented on mobile/src/components/bottomTabNavigator/BottomTabNavigator.tsx
> +        <Icon name="Compass" height={SIZE} width={SIZE} fill={PRIMARY_COLOR} />
In case the size is too big/small we can change it from there

2022-04-26 07:29 UTC, Dulaya commented
* put marginTop: 'auto' inside your container. This will push your navbar to the bottom.
* You don't need the shadow because your navbar will always be on the bottom.
* Instead of using SIZE, make it a mandatory type and force the user to input iconSize.
   * in BottomTabNavigator.type.ts:
      export type TBottomTabNavigatorProps = {
         iconSize: number,
      }
* Optional: Allow user to pass color into each fill of the icons via props.
* Optional: Let the user put in the values as props but use default number. 
   Whoever will build the Home screen should be the one providing value.

2022-04-26 07:29 UTC, Dulaya commented
* put marginTop: 'auto' inside your container. This will push your navbar to the bottom.
* You don't need the shadow because your navbar will always be on the bottom.
* Instead of using SIZE, make it a mandatory type and force the user to input iconSize.
   * in BottomTabNavigator.type.ts:
      export type TBottomTabNavigatorProps = {
         iconSize: number,
      }
* Optional: Allow user to pass color into each fill of the icons via props.
* Optional: Let the user put in the values as props but use default number. 
   Whoever will build the Home screen should be the one providing value.

2022-04-26 07:30 UTC, Dulaya approved these changes

2022-04-26 23:24 UTC, merged